Repository brazil-data-cube/stac.py, pull requests merged in 2020-09, with the labels that each got.

#40 Review for release 0.9.0-0
  .gitignore
  .readthedocs.yml
  .travis.yml
  CHANGES.rst
  INSTALL.rst
  LICENSE
  MANIFEST.in
  README.rst
  RUNNING.rst
  doc/sphinx/conf.py
  docs/sphinx/Makefile
  docs/sphinx/_static/stac.css
  docs/sphinx/api.rst
  docs/sphinx/conf.py
  docs/sphinx/img/favicon.ico
  docs/sphinx/img/logo-bdc.png
  docs/sphinx/index.rst
  docs/sphinx/installation.rst
  docs/sphinx/license.rst
  docs/sphinx/make.bat
  pytest.ini
  run-tests.sh
  setup.cfg
  setup.py
  tests/__init__.py
  tests/stac_tests/__init__.py
Labels: release

#43 Close #42
  stac/utils.py
Labels: bug

#45 Release v0.9.0-3
  .travis.yml
  CHANGES.rst
  INSTALL.rst
  README.rst
  docs/sphinx/history.rst
  docs/sphinx/index.rst
  docs/sphinx/installation.rst
  docs/sphinx/usage.rst
  setup.py
  stac/version.py
Labels: enhancement

#46 Merging branch b-0.9.0 into master inn order to update Travis CI config file
  .readthedocs.yml
  .travis.yml
  CHANGES.rst
  INSTALL.rst
  README.rst
  docs/sphinx/history.rst
  docs/sphinx/index.rst
  docs/sphinx/installation.rst
  docs/sphinx/usage.rst
  setup.py
  stac/version.py
Labels: enhancement

#47 Improvements to how objects are displayed on jupyter notebook
  MANIFEST.in
  examples/ex-01.py
  examples/jupyter-ex-01.ipynb
  requirements.txt
  setup.py
  stac/collection.py
  stac/item.py
  stac/stac.py
  stac/templates/collection.html
  stac/templates/item.html
  stac/templates/itemcollection.html
  stac/utils.py
Labels: enhancement

#50 Add ItemCollection iterator and Item read function
  CHANGES.rst
  stac/item.py
  stac/version.py
Labels: enhancement

#51 Merge Version 0.9.0-5 into master
  CHANGES.rst
  MANIFEST.in
  examples/ex-01.py
  examples/jupyter-ex-01.ipynb
  requirements.txt
  setup.py
  stac/collection.py
  stac/item.py
  stac/stac.py
  stac/templates/collection.html
  stac/templates/item.html
  stac/templates/itemcollection.html
  stac/utils.py
  stac/version.py
Labels: documentation
