Repository brazil-data-cube/stac.py, pull requests merged in 2021-03, with the labels that each got.

#67 Multiple fixes and usage improvements
  stac/catalog.py
  stac/collection.py
  stac/item.py
  stac/stac.py
  stac/utils.py
  stac/version.py
Labels: enhancement

#72 Improvements on stac.py - read partial raster and download entire item
  setup.py
  stac/item.py
Labels: enhancement

#76 Improve stac search - common way to build minimum bounding region
  CHANGES.rst
  stac/collection.py
  stac/item.py
  stac/stac.py
  stac/utils.py
  stac/version.py
Labels: enhancement

#79 Add shapely as required dependency
  CHANGES.rst
  setup.py
  stac/version.py
Labels: bug

#80 Update tests for bbox
  stac/utils.py
  tests/stac_tests/test_stac.py
Labels: test

#77 Merge branch b-0.9.0 into master
  CHANGES.rst
  setup.py
  stac/collection.py
  stac/item.py
  stac/stac.py
  stac/utils.py
  stac/version.py
  tests/stac_tests/test_stac.py
Labels: release
